### ISSUE TITLE
Make blog and about pages

### ISSUE THREAD

**Issue by josephmilla** [acm-uiuc/icpc-web#15]
Instead of separating announcements and practices, why not put them into a single page called blog? Then we should probably have an about page that shows the current members, officers, past awards, and other activities.

**Comment by wackytobaccy** [comment]
According to Uttam's spec, we should have announcements and practices. About pages may come later. You can ask Uttam if we need one. Please don't make issues on a whim as they fill up my GitHub notifications. If you have suggestions or questions that are not related to the existing code, just message me or email the group.
