### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by wackytobaccy** [acm-uiuc/icpc-web#4]
The navigation bar and site container need a small amount of responsiveness when the screen size is small, i.e. for netbook screens. This should be done after the CSS is refactored which should be done after all the pages and templates have been written.

**Comment by josephmilla** [comment]
Did Yong upload the files already?

**Comment by wackytobaccy** [comment]
Yes. They're in the readme.

**Comment by josephmilla** [comment]
I'll handle the styling. I haven't had time for this lately, sorry.

**Comment by wackytobaccy** [comment]
Do you mean look and feel or responsiveness? I think you should work on responsiveness first, then we can find a look and feel that Yong/Uttam like.

**Comment by josephmilla** [comment]
Responsiveness is now fixed. I'll continue styling...
